/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedVideosIdIndexRouteImport } from './routes/_authenticated/videos.$id.index'
import { Route as AuthenticatedVideosIdRenderRouteImport } from './routes/_authenticated/videos.$id.render'
import { Route as AuthenticatedVideosIdVersionsRouteImport } from './routes/_authenticated/videos.$id.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideosIdIndexRoute =
  AuthenticatedVideosIdIndexRouteImport.update({
    id: '/videos/$id/',
    path: '/videos/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVideosIdRenderRoute =
  AuthenticatedVideosIdRenderRouteImport.update({
    id: '/videos/$id/render',
    path: '/videos/$id/render',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVideosIdVersionsRoute =
  AuthenticatedVideosIdVersionsRouteImport.update({
    id: '/videos/$id/versions',
    path: '/videos/$id/versions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/videos/$id/render': typeof AuthenticatedVideosIdRenderRoute
  '/videos/$id/versions': typeof AuthenticatedVideosIdVersionsRoute
  '/videos/$id/': typeof AuthenticatedVideosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/videos/$id/render': typeof AuthenticatedVideosIdRenderRoute
  '/videos/$id/versions': typeof AuthenticatedVideosIdVersionsRoute
  '/videos/$id': typeof AuthenticatedVideosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/videos/$id/render': typeof AuthenticatedVideosIdRenderRoute
  '/_authenticated/videos/$id/versions': typeof AuthenticatedVideosIdVersionsRoute
  '/_authenticated/videos/$id/': typeof AuthenticatedVideosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/upload'
    | '/auth/callback'
    | '/videos/$id/render'
    | '/videos/$id/versions'
    | '/videos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/upload'
    | '/auth/callback'
    | '/videos/$id/render'
    | '/videos/$id/versions'
    | '/videos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/upload'
    | '/auth/callback'
    | '/_authenticated/videos/$id/render'
    | '/_authenticated/videos/$id/versions'
    | '/_authenticated/videos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videos/$id/': {
      id: '/_authenticated/videos/$id/'
      path: '/videos/$id'
      fullPath: '/videos/$id/'
      preLoaderRoute: typeof AuthenticatedVideosIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos/$id/render': {
      id: '/_authenticated/videos/$id/render'
      path: '/videos/$id/render'
      fullPath: '/videos/$id/render'
      preLoaderRoute: typeof AuthenticatedVideosIdRenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos/$id/versions': {
      id: '/_authenticated/videos/$id/versions'
      path: '/videos/$id/versions'
      fullPath: '/videos/$id/versions'
      preLoaderRoute: typeof AuthenticatedVideosIdVersionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedVideosIdRenderRoute: typeof AuthenticatedVideosIdRenderRoute
  AuthenticatedVideosIdVersionsRoute: typeof AuthenticatedVideosIdVersionsRoute
  AuthenticatedVideosIdIndexRoute: typeof AuthenticatedVideosIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedVideosIdRenderRoute: AuthenticatedVideosIdRenderRoute,
  AuthenticatedVideosIdVersionsRoute: AuthenticatedVideosIdVersionsRoute,
  AuthenticatedVideosIdIndexRoute: AuthenticatedVideosIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
